<a href="https://colab.research.google.com/github/Gkdas2k1/CognoRise-Infotech/blob/main/Spam_Email_Detection_Cognorise_Task3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import nltk
import re
import seaborn as sns
import matplotlib.pyplot as plt
nltk.download('stopwords')
nltk.download('punkt')
df = pd.read_csv('spam.csv', encoding='latin-1')
df

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


Category                                            Message
0         ham  Go until jurong point, crazy.. Available only ...
1         ham                      Ok lar... Joking wif u oni...
2        spam  Free entry in 2 a wkly comp to win FA Cup fina...
3         ham  U dun say so early hor... U c already then say...
4         ham  Nah I don't think he goes to usf, he lives aro...
...       ...                                                ...
5567     spam  This is the 2nd time we have tried 2 contact u...
5568      ham              Will ü b going to esplanade fr home?
5569      ham  Pity, * was in mood for that. So...any other s...
5570      ham  The guy did some bitching but I acted like i'd...
5571      ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [2]:
df = df.replace('ham', 'non_spam')

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5572 entries, 0 to 5571
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype 
---  ------    --------------  ----- 
 0   Category  5572 non-null   object
 1   Message   5572 non-null   object
dtypes: object(2)
memory usage: 87.2+ KB


In [5]:
df['Category'].value_counts()

Category
non_spam    4825
spam         747
Name: count, dtype: int64

In [6]:
df['Category']=df['Category'].map({'non_spam':0, 'spam':1})

In [8]:
tweets = df['Message']
from nltk import TweetTokenizer
tk = TweetTokenizer()
tweets = tweets.apply(lambda x:tk.tokenize(x)).apply(lambda x:' '.join(x))
tweets

0       Go until jurong point , crazy .. Available onl...
1                         Ok lar ... Joking wif u oni ...
2       Free entry in 2 a wkly comp to win FA Cup fina...
3       U dun say so early hor ... U c already then sa...
4       Nah I don't think he goes to usf , he lives ar...
                              ...                        
5567    This is the 2nd time we have tried 2 contact u...
5568              Will à ¼ b going to esplanade fr home ?
5569    Pity , * was in mood for that . So ... any oth...
5570    The guy did some bitching but I acted like i'd...
5571                          Rofl . Its true to its name
Name: Message, Length: 5572, dtype: object

In [9]:
tweets = tweets.str.replace('[^a-zA-Z0-9]+',' ')
tweets

0       Go until jurong point , crazy .. Available onl...
1                         Ok lar ... Joking wif u oni ...
2       Free entry in 2 a wkly comp to win FA Cup fina...
3       U dun say so early hor ... U c already then sa...
4       Nah I don't think he goes to usf , he lives ar...
                              ...                        
5567    This is the 2nd time we have tried 2 contact u...
5568              Will à ¼ b going to esplanade fr home ?
5569    Pity , * was in mood for that . So ... any oth...
5570    The guy did some bitching but I acted like i'd...
5571                          Rofl . Its true to its name
Name: Message, Length: 5572, dtype: object

In [10]:
from nltk.tokenize import word_tokenize
tweets = tweets.apply(lambda x: ' '.join([w for w in word_tokenize(x) if len(x)>=3]))
tweets

0       Go until jurong point , crazy .. Available onl...
1                         Ok lar ... Joking wif u oni ...
2       Free entry in 2 a wkly comp to win FA Cup fina...
3       U dun say so early hor ... U c already then sa...
4       Nah I do n't think he goes to usf , he lives a...
                              ...                        
5567    This is the 2nd time we have tried 2 contact u...
5568              Will à ¼ b going to esplanade fr home ?
5569    Pity , * was in mood for that . So ... any oth...
5570    The guy did some bitching but I acted like i '...
5571                          Rofl . Its true to its name
Name: Message, Length: 5572, dtype: object

In [11]:
from nltk.stem import SnowballStemmer
ss = SnowballStemmer('english')
tweets = tweets.apply(lambda x:[ss.stem(i.lower()) for i in tk.tokenize(x)]).apply(lambda x:' '.join(x))
tweets

0       go until jurong point , crazi .. avail onli in...
1                           ok lar ... joke wif u oni ...
2       free entri in 2 a wkli comp to win fa cup fina...
3       u dun say so earli hor ... u c alreadi then sa...
4       nah i do n't think he goe to usf , he live aro...
                              ...                        
5567    this is the 2nd time we have tri 2 contact u ....
5568                  will ã ¼ b go to esplanad fr home ?
5569    piti , * was in mood for that . so ... ani oth...
5570    the guy did some bitch but i act like i ' d be...
5571                            rofl . it true to it name
Name: Message, Length: 5572, dtype: object

In [12]:
from nltk.corpus import stopwords
sw = stopwords.words('english')
tweets = tweets.apply(lambda x: [i for i in word_tokenize(x) if i not in sw]).apply(lambda x: ' '.join(x))
tweets

0       go jurong point , crazi .. avail onli bugi n g...
1                           ok lar ... joke wif u oni ...
2       free entri 2 wkli comp win fa cup final tkts 2...
3             u dun say earli hor ... u c alreadi say ...
4              nah n't think goe usf , live around though
                              ...                        
5567    2nd time tri 2 contact u . u â £ 750 pound pri...
5568                          ã ¼ b go esplanad fr home ?
5569                    piti , * mood . ... ani suggest ?
5570    guy bitch act like ' interest buy someth els n...
5571                                     rofl . true name
Name: Message, Length: 5572, dtype: object

In [13]:
from sklearn.feature_extraction.text import TfidfVectorizer
vec = TfidfVectorizer()
data = vec.fit_transform(tweets)
data

<5572x7319 sparse matrix of type '<class 'numpy.float64'>'
	with 47715 stored elements in Compressed Sparse Row format>

In [14]:
print(data)

  (0, 6988)	0.19116071284724703
  (0, 1083)	0.34605452965067324
  (0, 3130)	0.16042179773034368
  (0, 1875)	0.2923482650508795
  (0, 1636)	0.33034645422832953
  (0, 3877)	0.2923482650508795
  (0, 7167)	0.23198437013180062
  (0, 3168)	0.19080691239010156
  (0, 1638)	0.2923482650508795
  (0, 4771)	0.16575600647079516
  (0, 1271)	0.260932114206192
  (0, 2083)	0.26799541190547166
  (0, 5083)	0.23629334920366546
  (0, 3766)	0.34605452965067324
  (0, 3092)	0.13871883163569262
  (1, 4769)	0.5652772724911168
  (1, 7088)	0.4437939483438497
  (1, 3733)	0.4749504100110151
  (1, 3909)	0.42225952924743965
  (1, 4742)	0.2821835122902816
  (2, 378)	0.15111503670608792
  (2, 79)	0.23434695445324913
  (2, 1155)	0.1668292599267376
  (2, 5345)	0.1668292599267376
  (2, 6704)	0.12404862119091215
  :	:
  (5567, 4771)	0.17710563695941772
  (5568, 2627)	0.6650056778292512
  (5568, 2917)	0.5738678852280512
  (5568, 3380)	0.3744439687897732
  (5568, 3092)	0.29704345304299484
  (5569, 5034)	0.6038288697475673
  

In [15]:
data.shape

(5572, 7319)

In [16]:
y = df['Category'].values
y

array([0, 0, 1, ..., 0, 0, 0])

In [17]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(data,y,test_size=0.30,random_state=42)

In [19]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import BernoulliNB
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import AdaBoostClassifier
knn=KNeighborsClassifier(n_neighbors=5)
bayes=BernoulliNB()
model=SVC()
forest=RandomForestClassifier()
tree=DecisionTreeClassifier()
logreg = LogisticRegression()
adaboost = AdaBoostClassifier()
lst=[knn,bayes,model,forest,tree,logreg,adaboost]

In [20]:
for i in lst:
  print('Model is',i)
  i.fit(x_train,y_train)
  y_pred=i.predict(x_test)
  y_pred
  print(y_pred)
  print("CM is")
  print(confusion_matrix(y_test,y_pred))
  print("Accurcay score is",accuracy_score(y_test,y_pred))
  print("Classification report is")
  print(classification_report(y_test,y_pred))
  print('*'*100)

Model is KNeighborsClassifier()
[0 0 0 ... 0 0 0]
CM is
[[1448    0]
 [ 166   58]]
Accurcay score is 0.9007177033492823
Classification report is
              precision    recall  f1-score   support

           0       0.90      1.00      0.95      1448
           1       1.00      0.26      0.41       224

    accuracy                           0.90      1672
   macro avg       0.95      0.63      0.68      1672
weighted avg       0.91      0.90      0.87      1672

****************************************************************************************************
Model is BernoulliNB()
[0 0 0 ... 0 1 0]
CM is
[[1443    5]
 [  32  192]]
Accurcay score is 0.9778708133971292
Classification report is
              precision    recall  f1-score   support

           0       0.98      1.00      0.99      1448
           1       0.97      0.86      0.91       224

    accuracy                           0.98      1672
   macro avg       0.98      0.93      0.95      1672
weighted avg       

In [22]:
x_test[0:3]

<3x7319 sparse matrix of type '<class 'numpy.float64'>'
	with 34 stored elements in Compressed Sparse Row format>

In [32]:
y_test[0:15]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1])

In [33]:
pred = logreg.predict(x_test[0:15])
for i in pred:
  if i==1:
    print('Spam')
  else:
    print('Non Spam')

Non Spam
Non Spam
Non Spam
Non Spam
Non Spam
Non Spam
Non Spam
Non Spam
Non Spam
Non Spam
Non Spam
Non Spam
Non Spam
Non Spam
Spam
